version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore:"
    reviewers:
      - "Home-Office-Digital/hoos-engineering"
    labels:
      - "dependencies"
      - "patch"
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore:"
    reviewers:
      - "Home-Office-Digital/hoos-engineering"
    labels:
      - "dependencies"
      - "patch"